[package]
name = "launchk"
version = "0.1.0"
authors = ["David Stancu <dstancu@nyu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.15.0"

[build-dependencies]
bindgen = "0.53.1"